name: continuous-build
on: push

# Testing our first workflow

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: echo "hello forom step1, job1 of workflow1"
      - name: step2
        run:  echo "hello from baizura"
        -run: echo "hello from step3"
        -name: my step4 for testing multiple lines of execution
          run:|
          ls -l
          pwd
          sudo cat/etc/os-release
          uname -a
          echo "final step4 execution done"
