name: continous-build
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
     - main
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
# Testing our first workflow

env:
  name: Baizura
jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      environment: dev
      name: Siti
    steps:
      - name: step1
        run: |
          echo "hello from $name, job1 of workflow1, running from environment $environment with status $open"
          sleep 30
          hostname
      - name: my step2
        run: |
          echo "hello from $name"
          sleep 10
      - run: |
          echo "hello from step3"
          sleep 10
      - name: my step4 for testing multiple lines of code execution
        run: |
          ls -l
          pwd
          sudo cat /etc/os-release
          uname -a
          echo "final step4 execution done"
  test: 
    runs-on: self-hosted
    env:
      environment: staging
      status: open
    steps:
      - name: step1
        run: |
           echo "hello from $name, job 2 of workflow1, running from environment $environment with status $status"
           sleep 30
           hostname
      - name: my step2
        run: |
          echo "hello from $name"  
          sleep 10
